title: Yash Pramod Kulkarni
logo: /assets/img/portfolio_pic.png
description: Automation, Embedded Systems, IoT & Machine Learning Enthusiast | Computer Vision & Robotics
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
